spring:
  datasource: #数据库的配置
    username: root #数据库的账号
    password: 123456 #数据库的密码
    url: jdbc:mysql://localhost:3306/room?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai

  jackson: # json序列号配置
    property-naming-strategy: UPPER_CAMEL_CASE #设置大写开头的命名风格
    date-format: yyyy-MM-dd HH:mm:ss #设置标准的时间格式
    time-zone: Asia/Shanghai #时间对于的时区
  servlet:
    multipart: #文件的上传配置
      max-request-size: 10000MB #请求的最大报文长度不能超过10000MB
      max-file-size: 10024MB #上传的文件最大不能超过10024MB


mybatis-plus: #操作数据库的ORM框架 mybatis
  mapper-locations: mapper/*.xml #配置对于的mapper文件位置
  global-config:  #mybatis的全局配置
    db-config:    #数据库的配置
      table-prefix:   #表前面是否加前缀  如果不配置为空 会导致查询的sql表前面带有特定 前缀
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false         #是否转换成大小写
  type-aliases-package: com.room.entity  #实体存储的包位置
server:
  port: 8080